### ISSUE TITLE
Ver 1.0.0 does not load

### ISSUE THREAD

**Issue by help137** [Magnum97/BankSettings#3]
The new version 1.0.0 is not loading at all, it doesn't even show up in the list of add-ons in game. The issue appears to be that the folder name in the archive now has "-master" appended to it, but the name in the manifest file does not. Changing the folder name fixes the issue. Also, the version in the various files still says "0.0.7"  and the API appears to still be an older one, listing 100033 instead of the current 100034.

(Been using this add-on since you released it and immediately noticed it's absence in game!)

**Comment by Magnum97** [comment]
> (Been using this add-on since you released it and immediately noticed it's absence in game!)

Thank you! It is encouraging to know that the effort is appriciated. Also thank you for the feedback- i have not had much time recently for ESO, but I noticed it was not loaded as well. I will patch that and update it PDQ.
